using UnityEngine;
using UnityEngine.Networking;
using System.Collections;
using System.Collections.Generic;
using TMPro;
using System.Text.RegularExpressions;

/// <summary>
/// gameobject follows a path with diagloue 
/// </summary>

// Text tag effects was generated by AI
// https://gemini.google.com/share/4ab56755fbc2

// linking AI to google sheets
// https://gemini.google.com/share/e83ef3f4d00d
[System.Serializable]
public struct Waypoint
{
    public Transform targetTransform;
    public float waitTime;
    
    [TextArea(2, 5)]
    public string dialogueText; 
}

[RequireComponent(typeof(AudioSource))]
public class TutorialFollowPath : MonoBehaviour
{
    [Header("Google Sheets Setup")]
    public string sheetURL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vS0_hZ3F0hbX0W6UluFPqagRX76o1_C_MjZRToBaMjkonON9I9fpmpX2pyyf5azqzx6p2Wxh0RwXPUf/pub?output=tsv";

    [Header("Path Settings")]
    public List<Waypoint> waypoints = new List<Waypoint>();
    public float moveSpeed = 5f;
    public float rotationSpeed = 10f;

    [Header("Animation Integration")]
    public DogWalkAnimation walkAnimation;

    [Header("Dialogue Settings")]
    public TMP_Text floatingText;
    
    [Tooltip("The time in seconds between each letter appearing.")]
    public float textTypeSpeed = 0.05f; 
    
    [Tooltip("Tracks which waypoint the object is currently traveling to or acting upon.")]
    public int currentWaypointIndex = 0; 

    [Header("Animal Crossing Voice")]
    public AudioClip voiceBlip;
    [Range(0.5f, 2f)] public float minPitch = 0.8f;
    [Range(0.5f, 2f)] public float maxPitch = 1.2f;
    private AudioSource audioSource;

    [Header("Text Effects Settings")]
    public float waveSpeed = 5f;
    public float waveHeight = 10f;
    public float rainbowColorSpeed = 1f;
    public float shakeAmount = 2f;
    public float ghostFadeSpeed = 3f;
    [Range(0f, 1f)] public float glitchChance = 0.1f;
    public float glitchIntensity = 5f;

    [Header("Explosion Settings")]
    public float explosionForce = 50f;
    public float explosionGravity = 20f;
    private bool isExploding = false;
    private float explosionStartTime;

    private void Awake()
    {
        audioSource = GetComponent<AudioSource>();
        audioSource.playOnAwake = false;
    }

    private IEnumerator Start()
    {
        // 1. Download the Google Sheet data first
        if (!string.IsNullOrEmpty(sheetURL))
        {
            yield return StartCoroutine(FetchSheetData());
        }
        else
        {
            Debug.LogWarning("No Sheet URL provided! Proceeding with inspector data.");
        }

        // 2. Start moving only after data is loaded
        StartCoroutine(FollowPath());
    }

    private void Update()
    {
        AnimateSpecialText();
    }

    
    // AI
    private IEnumerator FetchSheetData()
    {
        using (UnityWebRequest www = UnityWebRequest.Get(sheetURL))
        {
            yield return www.SendWebRequest();

            if (www.result == UnityWebRequest.Result.ConnectionError || www.result == UnityWebRequest.Result.ProtocolError)
            {
                Debug.LogError("Error fetching Google Sheet: " + www.error);
            }
            else
            {
                ParseTSV(www.downloadHandler.text);
            }
        }
    }

    // AI
   private void ParseTSV(string data)
    {
        // 1. Sanity Check: Print the start of the data so we can see if it's HTML or a CSV
        Debug.Log("Raw Downloaded Data (First 100 chars):\n" + data.Substring(0, Mathf.Min(data.Length, 100)));

        // 2. Strip out invisible carriage returns that Windows/Mac sometimes add
        data = data.Replace("\r", "");
        
        // 3. Split into rows
        string[] rows = data.Trim().Split('\n');

        if (rows.Length <= 1) 
        {
            Debug.LogError("The downloaded file only has 1 line or is empty. Check your URL!");
            return;
        }

        int updatedCount = 0;

        // 4. Parse the rows
        for (int i = 1; i < rows.Length; i++)
        {
            int waypointIndex = i - 1;

            if (waypointIndex >= waypoints.Count)
            {
                Debug.LogWarning($"Skipped Sheet Row {i+1}: You need to add more waypoints in the Unity Inspector!");
                break;
            }

            // Split by Tab
            string[] columns = rows[i].Split('\t');

            if (columns.Length >= 2)
            {
                Waypoint updatedWaypoint = waypoints[waypointIndex];

                if (float.TryParse(columns[0].Trim().Trim('"'), out float parsedWaitTime))
                {
                    updatedWaypoint.waitTime = parsedWaitTime;
                }

                // This strips away any rogue double quotes that Google Sheets adds, THEN replaces the line breaks
                string cleanText = columns[1].Trim().Trim('"');
                updatedWaypoint.dialogueText = cleanText.Replace("\\n", "\n");
                
                waypoints[waypointIndex] = updatedWaypoint;
                
                updatedCount++;
                Debug.Log($"Success! Waypoint {waypointIndex} updated -> Time: {updatedWaypoint.waitTime} | Text: {updatedWaypoint.dialogueText}");
            }
            else
            {
                // If it fails, this will tell us exactly why!
                Debug.LogError($"Row {i+1} failed to split! It only found {columns.Length} column(s). The row looks like this: {rows[i]}");
            }
        }
        
        Debug.Log($"Finished! Successfully updated {updatedCount} waypoints.");
    }

    private IEnumerator FollowPath()
    {
        for (currentWaypointIndex = 0; currentWaypointIndex < waypoints.Count; currentWaypointIndex++)
        {
            Waypoint point = waypoints[currentWaypointIndex];

            // Turn on the walking animation while moving to the next point
            if (walkAnimation != null) 
            {
                walkAnimation.isWalking = true;
            }

            // Move towards the transform
            while (Vector3.Distance(transform.position, point.targetTransform.position) > 0.01f)
            {
                Vector3 directionToTarget = point.targetTransform.position - transform.position;
                
                // directionToTarget.y = 0; 

                if (directionToTarget != Vector3.zero) 
                {
                    Quaternion targetRotation = Quaternion.LookRotation(directionToTarget);
                    transform.rotation = Quaternion.Slerp(transform.rotation, targetRotation, rotationSpeed * Time.deltaTime);
                }

                transform.position = Vector3.MoveTowards(transform.position, point.targetTransform.position, moveSpeed * Time.deltaTime);
                yield return null; 
            }

            transform.position = point.targetTransform.position;

            // Trigger the dialogue for this specific waypoint
            if (walkAnimation != null)
            {
                walkAnimation.isWalking = false;
                walkAnimation.ResetPosture();
            }

            if (!string.IsNullOrEmpty(point.dialogueText))
            {
                yield return StartCoroutine(TypeText(point.dialogueText));
            }

            // Wait for the specified amount of time at this transform
            if (point.waitTime > 0)
            {
                yield return new WaitForSeconds(point.waitTime);
            }

            // Explode the special text at the end of the wait time before moving on
            TriggerExplosion();
            yield return new WaitForSeconds(1.5f); 
            
            isExploding = false;
            floatingText.maxVisibleCharacters = 0; 
            floatingText.text = "";
        }
        
        if (walkAnimation != null)
        {
            walkAnimation.isWalking = false;
            walkAnimation.ResetPosture();
        }

        Debug.Log("Path complete!");
    }

    // Slowly write out the text
    // Text effect
    private IEnumerator TypeText(string rawText)
    {
        string processedText = rawText;
        processedText = Regex.Replace(processedText, @"<rainbow>(.*?)</rainbow>", "<link=\"rainbow\">$1</link>");
        processedText = Regex.Replace(processedText, @"<wave>(.*?)</wave>", "<link=\"wave\">$1</link>");
        processedText = Regex.Replace(processedText, @"<shake>(.*?)</shake>", "<link=\"shake\">$1</link>");
        processedText = Regex.Replace(processedText, @"<ghost>(.*?)</ghost>", "<link=\"ghost\">$1</link>");
        processedText = Regex.Replace(processedText, @"<glitch>(.*?)</glitch>", "<link=\"glitch\">$1</link>");
        
        // Added explicit explode tag!
        processedText = Regex.Replace(processedText, @"<explode>(.*?)</explode>", "<link=\"explode\">$1</link>");

        floatingText.text = processedText;
        floatingText.ForceMeshUpdate();

        floatingText.maxVisibleCharacters = 0;
        int totalVisibleCharacters = floatingText.textInfo.characterCount;

        for (int i = 0; i <= totalVisibleCharacters; i++)
        {
            floatingText.maxVisibleCharacters = i;

            if (i > 0 && i <= floatingText.textInfo.characterCount)
            {
                char c = floatingText.textInfo.characterInfo[i - 1].character;
                if (c != ' ' && voiceBlip != null)
                {
                    audioSource.pitch = Random.Range(minPitch, maxPitch);
                    audioSource.PlayOneShot(voiceBlip, 0.5f);
                }
            }

            yield return new WaitForSeconds(textTypeSpeed);
        }
    }

    public void TriggerExplosion()
    {
        isExploding = true;
        explosionStartTime = Time.time;
    }

    // AI
    private void AnimateSpecialText()
    {
        if (floatingText == null || floatingText.textInfo == null || floatingText.textInfo.characterCount == 0) return;

        floatingText.ForceMeshUpdate();
        TMP_TextInfo textInfo = floatingText.textInfo;
        
        float timeSinceExplosion = Time.time - explosionStartTime;

        for (int i = 0; i < textInfo.characterCount; i++)
        {
            TMP_CharacterInfo charInfo = textInfo.characterInfo[i];
            if (!charInfo.isVisible) continue;

            int materialIndex = charInfo.materialReferenceIndex;
            int vertexIndex = charInfo.vertexIndex;

            Vector3[] vertices = textInfo.meshInfo[materialIndex].vertices;
            Color32[] vertexColors = textInfo.meshInfo[materialIndex].colors32;

            // --- 1. FIND TAGS FIRST ---
            bool hasAnyTag = false;
            bool isRainbow = false, isWave = false, isShake = false, isGhost = false, isGlitch = false;

            foreach (TMP_LinkInfo link in textInfo.linkInfo)
            {
                if (i >= link.linkTextfirstCharacterIndex && i < link.linkTextfirstCharacterIndex + link.linkTextLength)
                {
                    hasAnyTag = true;
                    string linkId = link.GetLinkID();
                    
                    if (linkId == "rainbow") isRainbow = true;
                    if (linkId == "wave") isWave = true;
                    if (linkId == "shake") isShake = true;
                    if (linkId == "ghost") isGhost = true;
                    if (linkId == "glitch") isGlitch = true;
                    // If it's "explode", it triggers hasAnyTag to be true, which is all we need!
                }
            }

            // --- 2. EXPLOSION OVERRIDE ---
            if (isExploding)
            {
                // Fade out ALL text smoothly during the explosion phase
                byte fadeAlpha = (byte)Mathf.Clamp(255 - (timeSinceExplosion * 150), 0, 255);
                for (int v = 0; v < 4; v++) vertexColors[vertexIndex + v].a = fadeAlpha;

                // BUT if the character has a tag, physically explode it outward!
                if (hasAnyTag)
                {
                    Random.InitState(i * 100); 
                    Vector3 randomDir = new Vector3(Random.Range(-1f, 1f), Random.Range(0.5f, 1.5f), 0).normalized;
                    
                    Vector3 explosionOffset = randomDir * explosionForce * timeSinceExplosion;
                    explosionOffset.y -= explosionGravity * (timeSinceExplosion * timeSinceExplosion); 

                    Matrix4x4 matrix = Matrix4x4.Rotate(Quaternion.Euler(0, 0, Random.Range(-300f, 300f) * timeSinceExplosion));
                    Vector3 center = (vertices[vertexIndex + 0] + vertices[vertexIndex + 2]) / 2f;

                    for (int v = 0; v < 4; v++)
                    {
                        vertices[vertexIndex + v] = center + matrix.MultiplyPoint3x4(vertices[vertexIndex + v] - center) + explosionOffset;
                    }
                }
                
                continue; // Skip the standard wobbles and shakes if we are exploding
            }

            // --- 3. STANDARD LINK EFFECTS ---
            if (isRainbow)
            {
                float hue = (Time.time * rainbowColorSpeed + i * 0.1f) % 1f;
                Color32 charColor = Color.HSVToRGB(hue, 1f, 1f);
                for (int v = 0; v < 4; v++) vertexColors[vertexIndex + v] = charColor;
            }

            if (isWave || isRainbow)
            {
                float waveOffset = Mathf.Sin(Time.time * waveSpeed + i * 1f) * waveHeight;
                for (int v = 0; v < 4; v++) vertices[vertexIndex + v].y += waveOffset;
            }

            if (isShake)
            {
                Vector3 jitterOffset = new Vector3(Random.Range(-shakeAmount, shakeAmount), Random.Range(-shakeAmount, shakeAmount), 0);
                for (int v = 0; v < 4; v++) vertices[vertexIndex + v] += jitterOffset;
            }

            if (isGhost)
            {
                float alphaFloat = (Mathf.Sin(Time.time * ghostFadeSpeed + i) + 1f) / 2f;
                byte alphaByte = (byte)(alphaFloat * 255);
                for (int v = 0; v < 4; v++) vertexColors[vertexIndex + v].a = alphaByte;
            }

            if (isGlitch)
            {
                if (Random.value < glitchChance)
                {
                    Vector3 glitchOffset = new Vector3(Random.Range(-glitchIntensity, glitchIntensity), Random.Range(-glitchIntensity, glitchIntensity), 0);
                    Color32 glitchColor = Random.value > 0.5f ? Color.cyan : Color.magenta;

                    for (int v = 0; v < 4; v++)
                    {
                        vertices[vertexIndex + v] += glitchOffset;
                        vertexColors[vertexIndex + v] = glitchColor;
                    }
                }
            }
        }

        floatingText.UpdateVertexData(TMP_VertexDataUpdateFlags.Vertices | TMP_VertexDataUpdateFlags.Colors32);
    }
}